name: Discord Commit Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "New Commits to Main Branch"
          embed-description: |
            **Commits:**
            ${{ github.event.commits[0].message }}

            **Author:** ${{ github.event.commits[0].author.name }}
            **Repository:** ${{ github.repository }}

            [View Commit]({{ github.event.commits[0].url }})
          embed-color: 5814783
