name: Discord Commit Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Discord Webhook
        id: check-webhook
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "webhook_present=false" >> $GITHUB_OUTPUT
          else
            echo "webhook_present=true" >> $GITHUB_OUTPUT
          fi

      - name: Discord Notification
        if: steps.check-webhook.outputs.webhook_present == 'true'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "New Commits to Main Branch"
          embed-description: |
            **Commits:**
            ${{ github.event.commits[0].message }}

            **Author:** ${{ github.event.commits[0].author.name }}
            **Repository:** ${{ github.repository }}

            **Commit URL:** https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          embed-color: 5814783
